# Generated by Django 3.2.16 on 2022-11-14 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibilio', '0002_auto_20221114_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='idAuthor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bibilio.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='idEditor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bibilio.editor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='idGender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bibilio.gender'),
            preserve_default=False,
        ),
    ]
