# Generated by Django 3.2.16 on 2022-11-14 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibilio', '0004_auto_20221114_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ManyToManyField(to='bibilio.Profile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibilio.session')),
            ],
        ),
    ]
